doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations\before': '%kernel.project_dir%/migrations/before'
        'DoctrineMigrations\after': '%kernel.project_dir%/migrations/after'
        
    enable_profiler: false
